
version: '2.1'

volumes:
  db-data:

services:
  db:
    image: kartoza/postgis:13.0
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: on-failure
    healthcheck:
      test: "exit 0"

  dbbackups:
    image: kartoza/pg-backup:13.0
    environment:
      - DUMPPREFIX=PG_gis
      - POSTGRES_HOST=db
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_PORT=5432
      - STORAGE_BACKEND="S3"
      - ACCESS_KEY_ID=<put there>
      - SECRET_ACCESS_KEY="<put there>"
      - DEFAULT_REGION=us-west-2
      - BUCKET=<put there>
      - HOST_BASE=s3.amazonaws.com
      - HOST_BUCKET=%(bucket)s.s3.amazonaws.com
      - SSL_SECURE=True
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
